spring.application.name=springai
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
spring.ai.model.chat=ollama
spring.ai.ollama.chat.model=qwen2.5-coder:7b
# use this property when deploying in other servers. If ollama is running locally then it is not required.
#spring.ai.ollama.base-url=http://localhost:11434
spring.docker.compose.stop.command=down

spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=spring-ai-collection
